######################################################
# ---- (01.)LOGGING-CONFIGURATION ----
######################################################
logging:
  config: "classpath:log4j2-spring.xml"

######################################################
# ---- (02.)SERVER-PORT-CONFIGURATION ----
######################################################
server:
  port: 9005

######################################################
# ---- (03.)ACTUATOR-CONFIGURATION ----
######################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"

######################################################
# ---- (04.)EUREKA-CONFIGURATION ----
######################################################
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:9102/eureka/"

######################################################
# ---- (05.)SPRING-CONFIGURATION ----
######################################################
spring:
  # ---- (05.01.)SPRING-APPLICATION-NAMING-CONFIGURATION ----
  application:
    name: "microservice-calendrier"

  # ---- (05.02.)SPRING-DATASOURCE-CONFIGURATION ----
  datasource:
    url: "jdbc:mariadb://localhost:3306/krhonos3?createDatabaseIfNotExist=true"
    username: "root"
    password: "proote"
    driver-class-name: "org.mariadb.jdbc.Driver"
    sql-script-encoding: UTF-8
    #initialization-mode: always
    #initialize: true
    #data: "classpath:import.sql"
  # ---- (05.03.)SPRING-JPA-CONFIGURATION ----
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MariaDB53Dialect"

######################################################
# ---- (06.)SECURITY-CONFIGURATION ----
######################################################
#todo